[package]
name = "duprm"
version = "0.1.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]

[dependencies]
either = "~1.1"
env_logger = "~0.4.2"
futures = "~0.1.13"
futures-cpupool = "~0.1.5"
log = "~0.3.7"
num_cpus = "~1.4"
typed-arena = "~1.3"
